# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Edinet < Formula
  desc "CLI tool for EDINET API v2 - 金融庁 開示書類の検索・取得"
  homepage "https://github.com/planitaicojp/edinet-cli"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/planitaicojp/edinet-cli/releases/download/v0.2.0/edinet-cli_0.2.0_darwin_amd64.tar.gz"
      sha256 "509c5b8088d35fe1f5b06fd56b6e35a88a08f6d8f1a20afa7128389dd7c04aa3"

      define_method(:install) do
        bin.install "edinet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/planitaicojp/edinet-cli/releases/download/v0.2.0/edinet-cli_0.2.0_darwin_arm64.tar.gz"
      sha256 "8027112dbf502d96a4c37ad2028543147a66d9434a623cfbc2ebea99da669a35"

      define_method(:install) do
        bin.install "edinet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/planitaicojp/edinet-cli/releases/download/v0.2.0/edinet-cli_0.2.0_linux_amd64.tar.gz"
      sha256 "19e150247a4c31044470e1c3736d759e448eec1e466fac893af05ced35c68881"
      define_method(:install) do
        bin.install "edinet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/planitaicojp/edinet-cli/releases/download/v0.2.0/edinet-cli_0.2.0_linux_arm64.tar.gz"
      sha256 "5232a77bbb7eaf5cec6f956361cc77a6035973588cc63b556b85972e950548f0"
      define_method(:install) do
        bin.install "edinet"
      end
    end
  end
end
