# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Edinet < Formula
  desc "CLI tool for EDINET API v2 - 金融庁 開示書類の検索・取得"
  homepage "https://github.com/planitaicojp/edinet-cli"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/planitaicojp/edinet-cli/releases/download/v0.1.0/edinet-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "f858801b73355cf250dc0f201b778699cafcf2ef33901c14b9c0c32c274a6607"

      define_method(:install) do
        bin.install "edinet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/planitaicojp/edinet-cli/releases/download/v0.1.0/edinet-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "a3c900e1369514df865e62b4e37954513664c5d6bf8e01b72ba0792185c94619"

      define_method(:install) do
        bin.install "edinet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/planitaicojp/edinet-cli/releases/download/v0.1.0/edinet-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "4da8206e00841e8594ebb5f0ec30fd2eb17dbff3217613fc5deee93b1b054d95"
      define_method(:install) do
        bin.install "edinet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/planitaicojp/edinet-cli/releases/download/v0.1.0/edinet-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "63a41d507525937b65e2e05fa0ffa02f6aa66aef4632eb377b5890f9be38db32"
      define_method(:install) do
        bin.install "edinet"
      end
    end
  end
end
