# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Edinet < Formula
  desc "CLI tool for EDINET API v2 - 金融庁 開示書類の検索・取得"
  homepage "https://github.com/planitaicojp/edinet-cli"
  version "0.3.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/planitaicojp/edinet-cli/releases/download/v0.3.1/edinet-cli_0.3.1_darwin_amd64.tar.gz"
      sha256 "eadc32a3645ae75cc9da3c9a67e3010788697cf200d529d670ef00c9af630a1e"

      define_method(:install) do
        bin.install "edinet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/planitaicojp/edinet-cli/releases/download/v0.3.1/edinet-cli_0.3.1_darwin_arm64.tar.gz"
      sha256 "13eb28ed5faab1c71bb34f6f19a9de79100ceb2c90f4df8d96656335742ff892"

      define_method(:install) do
        bin.install "edinet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/planitaicojp/edinet-cli/releases/download/v0.3.1/edinet-cli_0.3.1_linux_amd64.tar.gz"
      sha256 "e5028bc746b889048977557140cc41a3e2683cd6aeec254ff82ba2bd9548f070"
      define_method(:install) do
        bin.install "edinet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/planitaicojp/edinet-cli/releases/download/v0.3.1/edinet-cli_0.3.1_linux_arm64.tar.gz"
      sha256 "7c82d5654f54d10f224065e610620ea4bd271918af35d5595fb99fccf5acc212"
      define_method(:install) do
        bin.install "edinet"
      end
    end
  end
end
