# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Freee < Formula
  desc "CLI tool for freee public API"
  homepage "https://planitaicojp.github.io/freee-cli-pages/"
  version "0.5.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/planitaicojp/freee-cli/releases/download/v0.5.3/freee-cli_0.5.3_darwin_amd64.tar.gz"
      sha256 "d767ea3d29373e00bf1a4599006118113daed5413b22b4e8f8fbe8d3e88f47f7"

      define_method(:install) do
        bin.install "freee"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/planitaicojp/freee-cli/releases/download/v0.5.3/freee-cli_0.5.3_darwin_arm64.tar.gz"
      sha256 "002d9b936e3032fd569b84d0ab7ec72d95ab1e44ed71c340cb43e29ef7fd57ed"

      define_method(:install) do
        bin.install "freee"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/planitaicojp/freee-cli/releases/download/v0.5.3/freee-cli_0.5.3_linux_amd64.tar.gz"
      sha256 "99077516d7e170071367ddbdad0df5ad9c505e4822f45194dce1debc4fe312ef"
      define_method(:install) do
        bin.install "freee"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/planitaicojp/freee-cli/releases/download/v0.5.3/freee-cli_0.5.3_linux_arm64.tar.gz"
      sha256 "ae7b736c5cab61ac03dfc4b0349ae8a7c35cb19193c7a21f2e5e3caca15f5ae2"
      define_method(:install) do
        bin.install "freee"
      end
    end
  end
end
