# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Freee < Formula
  desc "CLI tool for freee public API"
  homepage "https://planitaicojp.github.io/freee-cli-pages/"
  version "0.5.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/planitaicojp/freee-cli/releases/download/v0.5.3/freee-cli_0.5.3_darwin_amd64.tar.gz"
      sha256 "51fdeef0161fd114522516ecf30d0de6b21a1827945cd172a819c14c06a10197"

      define_method(:install) do
        bin.install "freee"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/planitaicojp/freee-cli/releases/download/v0.5.3/freee-cli_0.5.3_darwin_arm64.tar.gz"
      sha256 "300587ca8fef20073689a6c52bf96eb50da4c1dfe92148235422d20a50739910"

      define_method(:install) do
        bin.install "freee"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/planitaicojp/freee-cli/releases/download/v0.5.3/freee-cli_0.5.3_linux_amd64.tar.gz"
      sha256 "c45a6adfd05d18fcf65c9204d88a34a1b7321797bb9e10c9a5a7ba8e2b0887fb"
      define_method(:install) do
        bin.install "freee"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/planitaicojp/freee-cli/releases/download/v0.5.3/freee-cli_0.5.3_linux_arm64.tar.gz"
      sha256 "ffce8214e03f361d443b0b5c797cc2c5015a6ee7a24eb0d75c582620e08a1064"
      define_method(:install) do
        bin.install "freee"
      end
    end
  end
end
