# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gbizinfo < Formula
  desc "gBizINFO REST API CLI - 経済産業省 法人情報API CLIツール"
  homepage "https://github.com/planitaicojp/gbizinfo-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/planitaicojp/gbizinfo-cli/releases/download/v0.1.0/gbizinfo-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "ac3e8a3aaddee55100900d4523c42cd3d46e1b06cb92ef1310ba6639935cd13b"

      define_method(:install) do
        bin.install "gbizinfo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/planitaicojp/gbizinfo-cli/releases/download/v0.1.0/gbizinfo-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "7ce7b71ea4fea1f02be60d2044d42ee4f100b4b16a258af7fc3f20a493517ef6"

      define_method(:install) do
        bin.install "gbizinfo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/planitaicojp/gbizinfo-cli/releases/download/v0.1.0/gbizinfo-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "f55c99dfcbc65af7a9bab1667eb2f0e922a8ef4aec7fc7cc5644833047a70b32"
      define_method(:install) do
        bin.install "gbizinfo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/planitaicojp/gbizinfo-cli/releases/download/v0.1.0/gbizinfo-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "f1b9e21e9c903096fe98703904691e8f359c5e192941a4c4c21f8617efa46ff1"
      define_method(:install) do
        bin.install "gbizinfo"
      end
    end
  end
end
