# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gbizinfo < Formula
  desc "gBizINFO REST API CLI - 経済産業省 法人情報API CLIツール"
  homepage "https://github.com/planitaicojp/gbizinfo-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/planitaicojp/gbizinfo-cli/releases/download/v0.1.0/gbizinfo-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "aa71ea4bfdac77c017383f0be40745a4d11bdae24d47982a6bd39a663729738f"

      define_method(:install) do
        bin.install "gbizinfo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/planitaicojp/gbizinfo-cli/releases/download/v0.1.0/gbizinfo-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "a13f7fe21623263e361e9218b28f596597bfe0e4d168a8dc4eb22adbf319c192"

      define_method(:install) do
        bin.install "gbizinfo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/planitaicojp/gbizinfo-cli/releases/download/v0.1.0/gbizinfo-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "42f631ac63fb15da57b0c3408ad2e309fd53304b4dae195ef3ebd5fd5307b19b"
      define_method(:install) do
        bin.install "gbizinfo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/planitaicojp/gbizinfo-cli/releases/download/v0.1.0/gbizinfo-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "0e41f41ef213603e97def67fddad478e52cfa7b2699279bbab53a740063cf822"
      define_method(:install) do
        bin.install "gbizinfo"
      end
    end
  end
end
