# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HoujinCli < Formula
  desc "法人番号システム Web-API CLI tool"
  homepage "https://github.com/planitaicojp/houjin-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/planitaicojp/houjin-cli/releases/download/v0.1.0/houjin-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "966e5404103ba749c6f85cf2a0350d57ac6b0a5e5f2b8da4f10c427201daabe9"

      define_method(:install) do
        bin.install "houjin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/planitaicojp/houjin-cli/releases/download/v0.1.0/houjin-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "d687471e02a318ce9e58f2dd676d14518c9f398b95423cebfc1cd0285d1f9ba5"

      define_method(:install) do
        bin.install "houjin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/planitaicojp/houjin-cli/releases/download/v0.1.0/houjin-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "e03cf885321994e13a1f086cc221d72de26725daa1d175cad56d29157c7b977f"
      define_method(:install) do
        bin.install "houjin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/planitaicojp/houjin-cli/releases/download/v0.1.0/houjin-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "85979ed06b8f269cd2c6b8c799e7c848c8858cc5f47b19028648ecd883449d72"
      define_method(:install) do
        bin.install "houjin"
      end
    end
  end
end
