# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jplaw < Formula
  desc "e-Gov法令API CLI - 日本の法令を検索・取得するコマンドラインツール"
  homepage "https://github.com/planitaicojp/jplaw-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/planitaicojp/jplaw-cli/releases/download/v0.1.0/jplaw-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "dee98e69773d611f71592b5d25eebad562f4dd8353fa2e2ddc0b0183954ccefd"

      define_method(:install) do
        bin.install "jplaw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/planitaicojp/jplaw-cli/releases/download/v0.1.0/jplaw-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "54223b74f1198ba2225f1f18ac0d5e406f304366f18ed8ac3fa3249a1b66b293"

      define_method(:install) do
        bin.install "jplaw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/planitaicojp/jplaw-cli/releases/download/v0.1.0/jplaw-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "bca739c73fc6cb960af90a7b98e92174e0fc1b8a4b10dee859704f2eb0b8ea03"
      define_method(:install) do
        bin.install "jplaw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/planitaicojp/jplaw-cli/releases/download/v0.1.0/jplaw-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "718d5fe95686008f20298d442c527b432541d56756a111df9d0c0741380a73ff"
      define_method(:install) do
        bin.install "jplaw"
      end
    end
  end
end
