# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jpweather < Formula
  desc "気象庁の天気予報・防災情報を取得するCLIツール"
  homepage "https://github.com/planitaicojp/jpweather-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/planitaicojp/jpweather-cli/releases/download/v0.1.0/jpweather-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "4bacd83c455ee04deb2735b6c880c82f2d2c2a4f2774311a2f6bf42f3915b2e0"

      define_method(:install) do
        bin.install "jpweather"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/planitaicojp/jpweather-cli/releases/download/v0.1.0/jpweather-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "e42e4e8ba7a11204fbdf904b3a692f0410993d420bc174445a8c19608e24aa32"

      define_method(:install) do
        bin.install "jpweather"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/planitaicojp/jpweather-cli/releases/download/v0.1.0/jpweather-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "b650ea42a911eee97dbd63a823456340c9469d072246a26853e730da73cd9de3"
      define_method(:install) do
        bin.install "jpweather"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/planitaicojp/jpweather-cli/releases/download/v0.1.0/jpweather-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "550d4ca1d5989e18967f0fd7ed33f470018e4e94834f4297de61cad3aafdcefb"
      define_method(:install) do
        bin.install "jpweather"
      end
    end
  end
end
