# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LmCli < Formula
  desc "CLI tool for LINE Messaging API"
  homepage "https://planitaicojp.github.io/lm-cli-pages/"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/planitaicojp/lm-cli/releases/download/v0.4.0/lm-cli_0.4.0_darwin_amd64.tar.gz"
      sha256 "6fa33b2267e3f50287c20d5620a6e3d3d6179a6782e85a72392f8f8016d10138"

      define_method(:install) do
        bin.install "lm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/planitaicojp/lm-cli/releases/download/v0.4.0/lm-cli_0.4.0_darwin_arm64.tar.gz"
      sha256 "7b2744fda6bc4fa41463c19dee221394762ef4c9579dc1fd0ab7a6c49566a9f5"

      define_method(:install) do
        bin.install "lm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/planitaicojp/lm-cli/releases/download/v0.4.0/lm-cli_0.4.0_linux_amd64.tar.gz"
      sha256 "ee8c3470cedde82044e194cc29a274f9b92e6043b5c9f706de16d8ce100b0b5b"
      define_method(:install) do
        bin.install "lm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/planitaicojp/lm-cli/releases/download/v0.4.0/lm-cli_0.4.0_linux_arm64.tar.gz"
      sha256 "0c82fed10bd5a86e0eb6e467496f0b6f46dbe2b879b89ae11684b695629885c0"
      define_method(:install) do
        bin.install "lm"
      end
    end
  end
end
