# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mf < Formula
  desc "CLI tool for Money Forward Cloud APIs"
  homepage "https://planitaicojp.github.io/moneyforward-cli-pages/"
  version "0.2.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/planitaicojp/moneyforward-cli/releases/download/v0.2.1/moneyforward-cli_0.2.1_darwin_amd64.tar.gz"
      sha256 "e5d5fa04667ce9b092a36993a626262523431d798a099b3acdabe12191a99c94"

      define_method(:install) do
        bin.install "mf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/planitaicojp/moneyforward-cli/releases/download/v0.2.1/moneyforward-cli_0.2.1_darwin_arm64.tar.gz"
      sha256 "aa4ec4b8b63818d90def32ffe95df78531df9d715e44230f4362a3e766b220af"

      define_method(:install) do
        bin.install "mf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/planitaicojp/moneyforward-cli/releases/download/v0.2.1/moneyforward-cli_0.2.1_linux_amd64.tar.gz"
      sha256 "d5a967390968bda3e603884be73c6aec36907b08e96ccacc1365bc22bdae3ee0"
      define_method(:install) do
        bin.install "mf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/planitaicojp/moneyforward-cli/releases/download/v0.2.1/moneyforward-cli_0.2.1_linux_arm64.tar.gz"
      sha256 "9a959a3a15961e77dca7df0366623aef5013cf55f15fe1c09d9add3bbfee7e08"
      define_method(:install) do
        bin.install "mf"
      end
    end
  end

  test do
    system "#{bin}/mf", "version"
  end
end
