# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Resas < Formula
  desc "CLI tool for RESAS (Regional Economic Analysis System) API"
  homepage "https://github.com/planitaicojp/resas-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/planitaicojp/resas-cli/releases/download/v0.1.0/resas-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "341251d40b4153bf2d886de9e5afb5c0b03de11cbd05c4a2976fe578efdacf2b"

      define_method(:install) do
        bin.install "resas"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/planitaicojp/resas-cli/releases/download/v0.1.0/resas-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "46b68123b6768d490331e61b43344b435cfc885dbccdc0b0b98e3c4253a71335"

      define_method(:install) do
        bin.install "resas"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/planitaicojp/resas-cli/releases/download/v0.1.0/resas-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "2cab22ed79637e087d2590971d08d0386eade2261418dc1806f5844ea43f780f"
      define_method(:install) do
        bin.install "resas"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/planitaicojp/resas-cli/releases/download/v0.1.0/resas-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "5549f41fcae33ecda5a400ef21d541cef149836ebe2e97473e2375b5d4468abb"
      define_method(:install) do
        bin.install "resas"
      end
    end
  end
end
